### ISSUE TITLE
import { Message } from './compiled';  ts怎么引入js文件的呢

### ISSUE THREAD

**Issue by wangmiaoduan** [lixin59/protobuf-test-project#1]
// 定义要加载的 .proto 文件 URL
const protoUrl = '/path/to/your/message.proto';

import { Message } from './compiled';
ts怎么引入js文件的呢

这两个地方引入都会报错

**Comment by lixin59** [comment]
引入js报错最好的解决办法声明一个同名的.d.ts的文件，在这个文件中声明并导出 js 文件中的方法和变量, 脚本中有生成对应ts文件的脚本to-ts
[看这里](https://github.com/lixin59/protobuf-test-project/blob/master/packages/server/package.json)，最好不要直接引入proto文件，将该文件转成js之后再生成对应的ts文件，在ts项目里面就可以正常使用了

**Comment by lixin59** [comment]
> 引入js报错最好的解决办法声明一个同名的.d.ts的文件，在这个文件中声明并导出 js 文件中的方法和变量, 脚本中有生成对应ts文件的脚本to-ts
> [看这里](https://github.com/lixin59/protobuf-test-project/blob/master/packages/server/package.json)，最好不要直接引入proto文件，将该文件转成js之后再生成对应的ts文件，在ts项目里面就可以正常使用了

**Comment by lixin59** [comment]
> // 定义要加载的 .proto 文件 URL const protoUrl = '/path/to/your/message.proto';
> 
> import { Message } from './compiled'; ts怎么引入js文件的呢
> 
> 这两个地方引入都会报错

引入js报错最好的解决办法声明一个同名的.d.ts的文件，在这个文件中声明并导出 js 文件中的方法和变量, 脚本中有生成对应ts文件的脚本to-ts
[看这里](https://github.com/lixin59/protobuf-test-project/blob/master/packages/server/package.json)，最好不要直接引入proto文件，将该文件转成js之后再生成对应的ts文件，在ts项目里面就可以正常使用了
